#NAME: Connor Borden Chris Bachelor
#EMAIL: connorbo97@g.ucla.edu cbachelor@ucla.edu
lab3a: lab3a.c ext2_fs.h
	gcc -g lab3a.c -o lab3a


dist:	lab3a
	tar -zcvf lab3a-004603469.tar.gz Makefile ext2_fs.h lab3a.c README

clean: 
	rm -f lab3a-004603469.tar.gz lab3a
